// Generated by CoffeeScript 1.7.1
(function() {
  var BITSNPIECES, TRM, alert, badge, debug, help, info, log, rpr, teacup, warn, whisper;

  TRM = require('coffeenode-trm');

  rpr = TRM.rpr.bind(TRM);

  badge = 'CndTeacup';

  log = TRM.get_logger('plain', badge);

  info = TRM.get_logger('info', badge);

  whisper = TRM.get_logger('whisper', badge);

  alert = TRM.get_logger('alert', badge);

  debug = TRM.get_logger('debug', badge);

  warn = TRM.get_logger('warn', badge);

  help = TRM.get_logger('help', badge);

  BITSNPIECES = require('coffeenode-bitsnpieces');


  /* https://github.com/goodeggs/teacup */

  teacup = require('teacup');

  (function(_this) {
    return (function() {
      var my_name, name, _results;
      _results = [];
      for (name in teacup) {
        switch (name) {
          case 'renderable':
          case 'Teacup':
          case 'cede':
            continue;
          case 'render':
            my_name = name;
            break;
          default:
            my_name = name.toUpperCase();
        }
        _results.push(_this[my_name] = teacup[name].bind(_this));
      }
      return _results;
    });
  })(this)();

  this.TEXT_INPUT = function(Q, label) {
    if (Q == null) {
      Q = {};
    }
    if (label != null) {
      if (Q['label'] != null) {
        throw new Error("can't have both an unnamed argument and an option called 'label'");
      }
    } else {
      label = Q['label'];
      if (label == null) {
        throw new Error("must have either an unnamed argument and an option called 'label'");
      }
    }
    if (Q['placeholder'] == null) {
      Q['placeholder'] = label.replace(/\s*:\s*$/, '');
    }
    debug('TEXT_INPUT', Q);
    return this.LABEL((function(_this) {
      return function() {
        _this.SPAN({
          "class": 'label'
        }, label);
        return _this.INPUT(Q);
      };
    })(this));
  };

  this.EMAIL = function(Q) {
    var label;
    if (Q == null) {
      Q = {};
    }
    label = BITSNPIECES.pluck(Q, 'label', "your email:");
    if (Q['name'] == null) {
      Q['name'] = 'email';
    }
    if (Q['type'] == null) {
      Q['type'] = 'email';
    }
    if (Q['required'] == null) {
      Q['required'] = true;
    }
    return this.TEXT_INPUT(Q, label);
  };

  this.PASSWORD = function(Q) {
    var label;
    if (Q == null) {
      Q = {};
    }
    label = BITSNPIECES.pluck(Q, 'label', "your password:");
    if (Q['name'] == null) {
      Q['name'] = 'password';
    }
    if (Q['type'] == null) {
      Q['type'] = 'password';
    }
    if (Q['required'] == null) {
      Q['required'] = true;
    }
    return this.TEXT_INPUT(Q, label);
  };

  this.CONFIRM_PASSWORD = function(Q) {
    var label;
    if (Q == null) {
      Q = {};
    }
    label = BITSNPIECES.pluck(Q, 'label', "your password again:");
    if (Q['name'] == null) {
      Q['name'] = 'password-r';
    }
    if (Q['type'] == null) {
      Q['type'] = 'password';
    }
    if (Q['required'] == null) {
      Q['required'] = true;
    }
    return this.TEXT_INPUT(Q, label);
  };

  this.SUBMIT = function(Q) {
    var label;
    if (Q == null) {
      Q = {};
    }
    label = BITSNPIECES.pluck(Q, 'label', "submit");
    if (Q['type'] == null) {
      Q['type'] = 'submit';
    }
    return this.BUTTON(Q, label);
  };

}).call(this);
